#include"stdio.h"
int main()
{
	int i,j,ii,jj,kk,iii,jjj,kkk,judge=0,a,b=0,c=0,as2,as3,bs1,bs2,bs3,cs1,cs2,cs3,vis[9]={1,2,3,4,5,6,7,8,9};
	scanf("%d",&a);
	for(i=0;i<9;i++)
	    if(vis[i]==a)
	        vis[i]=0;
	a*=100;
	for(i=0;i<9;i++)
	{
		if(vis[i]==0)
		    continue;
		a+=vis[i]*10;
		as2=vis[i];
		vis[i]=0;
		for(j=0;j<9;j++)
		{
			if(vis[j]==0)
			    continue;
			a+=vis[j];
			as3=vis[j];
			vis[j]=0;
			for(ii=0;ii<9;ii++)
			{
				if(vis[ii]==0)
				    continue;
				b+=vis[ii]*100;
				bs1=vis[ii];
				vis[ii]=0;
				for(jj=0;jj<9;jj++)
				{
					if(vis[jj]==0)
					    continue ;
					b+=vis[jj]*10;
					bs2=vis[jj];
					vis[jj]=0;
					for(kk=0;kk<9;kk++)
					{
						if(vis[kk]==0)
						    continue;
						b+=vis[kk];
						bs3=vis[kk];
						vis[kk]=0;
						for(iii=0;iii<9;iii++)
						{
							if(vis[iii]==0)
							    continue;
							c+=vis[iii]*100;
							cs1=vis[iii];
							vis[iii]=0;
							for(jjj=0;jjj<9;jjj++)
							{
								if(vis[jjj]==0)
								    continue;
								c+=vis[jjj]*10;
								cs2=vis[jjj];
								vis[jjj]=0;
								for(kkk=0;kkk<9;kkk++)
								{
									if(vis[kkk]==0)
									    continue;
									c+=vis[kkk];
									if(b==2*a&&c==3*a)
									{
										printf("%d,%d,%d\n",a,b,c);
										judge=1;
									}     
									c-=vis[kkk];
								}
								vis[jjj]=cs2;
								c-=vis[jjj]*10;
								
							}
							vis[iii]=cs1;
							c-=vis[iii]*100;
						}
						vis[kk]=bs3;
						b-=vis[kk];
					}
					vis[jj]=bs2;
					b-=vis[jj]*10;
				}
				vis[ii]=bs1;
				b-=vis[ii]*100;
			}
			vis[j]=as3;
			a-=vis[j];
		}
		vis[i]=as2;
		a-=vis[i]*10;
	}
	if(judge==0)
	    printf("0,0,0\n");
	return 0;
}
